### PR TITLE
Add a script that securely downloads secret data from the server

### LINKED ISSUE #8: Keep secrets secret
# The Problem

Some information, like the password to the MongoDB instance and the `express-session` secret string, really really needs to not be public in this repository.

> Yep, still need to figure out how to keep secrets properly. Hng.

_Originally posted by @nok-ko in https://github.com/ShakeGuard/ShakeGuard/pull/7#discussion_r865424548_

## Potential Solutions

I thought about using GitHub's Secrets feature, but I'm not sure if it's worth spending the time to learn that – I can't find a brief overview and it seems geared more for running tests with GitHub Actions than general secret-keeping in dev environments.

## Proposed Solution

I can write a little Node.js script that uses [sftp](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol) to retrieve secret files from the server at `db.nokko.me` – all of you will just need to give me your SSH public keys, and the rest should be smooth sailing.

## To-Do List
Action items for me:
- [x] Set up user accounts for Tracy & Jay on `db.nokko.me`
- [x] Decide where the `.secrets` reference directory will live on the server, put some sort of example file there
    -  Decided on `/home/shakeguard/.secrets/`, there's an `example_secret.json` file inside that directory.
- [x] Write a Node script to retrieve the `.secrets` directory from the server via SFTP
    - [x] Find a good cross-platform SFTP library?
        - [This one](https://www.npmjs.com/package/ssh2-sftp-client) seems well-maintained and easy to use.
- [x] Make sure the Node script knows where to find private keys, on both Mac and Windows. 
    - ~~Maybe just check `git config`?~~
    - Decided to just look in `$HOME/.ssh/id_rsa` by default, and give users the option to use a different path when running the script.
- [ ] Test the script on all of the team members' computers:
    - [x] Katy
    - [ ] Alex
    - [ ] Jay
    - [ ] Tracy
- [x] Set up an account for the `shakeguard` user to do automated testing in the future.
- [x] Add `.secrets/` to the `.gitignore` file!

### PR DESCRIPTION
**Pull request by nok-ko**
Should close #8.

## What this PR should do:
- [x] Add a script that downloads secret data from `db.nokko.me`:
    - [x] The script should use its user's existing SSH credentials to authenticate.
    - [ ] The script should run properly on all of the platforms our team develops on:
        - [x] Mac
        - [ ] Windows
    - [x] The script should accept command-line arguments, allowing users to:
        - [x] Specify a different user to authenticate as.
        - [x] Specify a different private key file to use when authenticating.
- [x] Run the script before `npm start` is called (using the special `prestart` npm script.)
- [x] Add the `.secrets` directory to the `.gitignore` file to make sure nobody can commit it to the repo by accident.

## Other Notes
This PR adds a dependency: [`ssh2-sftp-client`](https://www.npmjs.com/package/ssh2-sftp-client). I think this is fine, but worth noting anyway.

### CODE REVIEW

**Comment by nok-ko** [comment]
@ArtfulJW, could you make sure the script works on Windows? Checkout this feature branch and run the script with `npm run prestart`, it should download the `.secrets` directory.

Both @ArtfulJW and @AlexLLKong, please look over the code for any errors or quality issues.

**Comment by nok-ko** [comment]
[Make the Node app log into the DB with user+pass authentication – figure out how to store secrets in the GH repo? (1hr)](https://trello.com/c/kEcL9jXy/60-make-the-node-app-log-into-the-db-with-userpass-authentication-figure-out-how-to-store-secrets-in-the-gh-repo-1hr)

**Review by AlexLLKong — APPROVED** [review]
LGTM!

**Comment by nok-ko** [comment]
👌

**Pull request merged**
